apiVersion: v1
kind: Secret
metadata:
  name: bank-core-secret
  namespace: minibank
type: Opaque
stringData:
  mysql-root-password: "change-me"
  mysql-app-username: "minibank_app"
  mysql-app-password: "change-me-app"
